[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''autocmd BufWritePre *.py execute('LspDocumentFormatSync')'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
  let g:lsp_settings_filetype_typescript = ['typescript-language-server', 'eslint-language-server', 'deno']
  let g:lsp_settings = {
  \  'pylsp-all': {
  \    'workspace_config': {
  \      'pylsp': {
  \        'configurationSources': ['flake8'],
  \        'plugins': {
  \          'autopep8': {
  \            'enabled': 0
  \          },
  \          'black': {
  \            'enabled': 1,
  \            'preview': 0
  \          },
  \          'flake8': {
  \            'enabled': 1
  \          },
  \          'mccabe': {
  \            'enabled': 0
  \          },
  \          'pycodestyle': {
  \            'enabled': 0
  \          },
  \          'pyflakes': {
  \            'enabled': 0
  \          },
  \          'pyls_isort': {
  \            'enabled': 1
  \          },
  \          'pylsp_mypy': {
  \            'enabled': 1
  \          },
  \          'yapf': {
  \            'enabled': 0
  \          }
  \        }
  \      }
  \    }
  \  }
  \}

'''
