[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_add = '''
  if system('uname') =~ 'darwin'  " mac
      let g:previm_open_cmd = 'open -a google\ chrome'
  elseif isdirectory('/mnt/c')    " wsl
      let g:previm_open_cmd = '/mnt/c/program\ files\ \(x86\)/google/chrome/application/chrome.exe'
      let g:previm_wsl_mode = 1
  endif 
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_i = 1
hook_source = '''
  inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"

  " allow modifying the completeopt variable, or it will
  " be overridden all the time
  let g:asyncomplete_auto_completeopt = 0

  set completeopt=menuone,noinsert,noselect,preview
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_i = 1

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c', 'cpp', 'javascript', 'typescript']
hook_source = '''ClangFormatAutoEnable'''

[[plugins]]
repo = 'kana/vim-operator-user'
on_ft = ['c', 'cpp', 'javascript', 'typescript']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascriptreact']
hook_source = '''autocmd BufWrite *.jsx :call preserve#Preserve(':normal ggVG=')'''













