version: 2
root-markers:
  - .git/
tools:
  prettier: &prettier
    format-command: 'npx prettier --write ${INPUT}'
    format-stdin: true
    root-markers:
      - .prettierrc.json
languages:
  typescript:
    - <<: *prettier
  typescriptreact:
    - <<: *prettier
